import { fetchTopicSummary } from "../clients/wikipediaClient.js";
import { validateLevel } from "./quizService.js";

const levelSentenceCounts = {
  1: 3,
  2: 4,
  3: 5,
  4: 6,
  5: 7
};

const generatedTemplates = {
  1: (topic) =>
    `${topic} is an interesting topic. People can learn simple words about it. It can help students talk about daily life.`,
  2: (topic) =>
    `${topic} is useful for English practice. Learners can read short texts, notice new words, and explain basic ideas about the topic.`,
  3: (topic) =>
    `${topic} can help learners build vocabulary and confidence. A short reading about this topic gives students context, examples, and useful phrases for conversation.`,
  4: (topic) =>
    `${topic} is a strong topic for deeper English practice. Learners can compare ideas, describe causes and effects, and use more precise vocabulary while discussing it.`,
  5: (topic) =>
    `${topic} gives advanced learners a chance to analyze ideas with nuance. They can evaluate different perspectives, summarize key points, and use sophisticated vocabulary in context.`
};

function splitSentences(text) {
  return String(text || "")
    .replace(/\s+/g, " ")
    .match(/[^.!?]+[.!?]+/g) || [];
}

function buildExternalReading(summary, level) {
  const sentenceCount = levelSentenceCounts[level] || 4;
  const sentences = splitSentences(summary.extract).slice(0, sentenceCount);

  return sentences.join(" ").trim() || summary.extract;
}

function buildGeneratedReading(topic, level) {
  const normalizedTopic = topic.trim();
  const template = generatedTemplates[level] || generatedTemplates[3];

  return template(normalizedTopic);
}

export async function generateReading({ topic, level }) {
  const parsedLevel = validateLevel(level);
  const normalizedTopic = String(topic || "").trim();

  if (!normalizedTopic) {
    const error = new Error("topic query parameter is required.");
    error.status = 400;
    throw error;
  }

  const externalSummary = await fetchTopicSummary(normalizedTopic);

  if (externalSummary) {
    return {
      topic: normalizedTopic,
      title: externalSummary.title,
      level: parsedLevel,
      text: buildExternalReading(externalSummary, parsedLevel),
      source: {
        type: "external",
        name: "Wikipedia REST API",
        url: externalSummary.url,
        note: "This reading is based on an external source and shortened by the API."
      }
    };
  }

  return {
    topic: normalizedTopic,
    title: normalizedTopic,
    level: parsedLevel,
    text: buildGeneratedReading(normalizedTopic, parsedLevel),
    source: {
      type: "generated",
      name: "Local reading generator",
      url: null,
      note: "No external source was available, so this reading was generated by the API."
    }
  };
}
